version: "3.8"

services:
  elvis-ip2-client:
    image: elvis-ip2/elvis-ip2-client:v1.0.0
    build: ./client
    container_name: elvis-ip2-client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
      - elvis-ip2-backend
    networks:
      - app-net

  elvis-ip2-backend:
    image: elvis-ip2/elvis-ip2-backend:v1.0.0
    build: ./backend
    container_name: elvis-ip2-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    depends_on: 
      - app-ip-mongo
    networks:
      - app-net

  app-ip-mongo:
    image: mongo
    container_name: app-mongo
    ports:
      - "27017:27017"
    networks:
      - app-net
    volumes:
      - type: volume
        source: app-mongo-data
        target: /data/db

networks:
  app-net:
    name: app-net
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.20.0.0/16 
          ip_range: 172.20.0.0/16 

volumes:
  app-mongo-data:
    driver: local
