version: "3.8"

services:
  client:
    build: ./client
    container_name: elvis-ip2-client
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: elvis-ip2-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/mydatabase

  mongo:
    image: mongo:4.4
    container_name: elvis-ip2-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
