---
- name: Ansible playbook that will dockerize the e-commerce app using ansible
  hosts: all
  become: true
  roles: 
    - frontend-deployment
    - setup-mongodb   
    - backend-deployment
    - github-setup
    